version: "3.7"

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: db
    tty: true
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db
      POSTGRES_PASSWORD: test123
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - project_network_local

  broker:
    container_name: broker
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    restart: unless-stopped
    ports:
      - '4369:4369'
      - '5551:5551'
      - '5552:5552'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=test123456
    networks:
      - project_network_local

networks:
  project_network_local:
    driver: bridge

volumes:
  db_data:
  broker: